# Generated by Django 3.2.4 on 2021-06-17 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catagory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catagory', models.CharField(max_length=50)),
                ('slug_catagory', models.SlugField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('describetion', models.TextField()),
                ('image', models.ImageField(upload_to='post_image')),
                ('slug_post', models.SlugField(default='')),
                ('catagory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.catagory')),
            ],
        ),
    ]
